---
- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Update Host
  apt: update_cache=yes

- name: Accept Java License
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Install Oracle Java 8
  apt: pkg={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default