---
#- name: Add Oracle Java Repository
#  shell: add-apt-repository -y ppa:webupd8team/java8

- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Update Host
  apt: update_cache=yes

- name: Accept Java License
#  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Install Oracle Java 8
  shell: DEBIAN_FRONTEND=noninteractive apt-get -y install oracle-java8-installer oracle-java8-set-default
  apt: pkg={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default