---
# The following installs sbt even though it's not really needed unless compiling an "uber" jar

# There are issues with the following, therfore changing from 'command' to 'shell'. The script works with command, but 'sbt.list' is not present
#- name: Add scala-sbt Repository
#  shell: echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list

# There are issues with the following, therfore changing to 'hkp://'
#- name: Add scala-sbt public key
#  apt_key:
#    id: 642AC823
#    keyserver: hkp://keyserver.ubuntu.com:80
#    state: present

#- name: Update Hosts
#  apt: update_cache=yes

#- name: Install Scala-sbt
#  apt: pkg=sbt state=installed update-cache=yes

- name: Download scala
  get_url: url=http://downloads.lightbend.com/scala/{{ scala_version }}/scala-{{ scala_version}}.deb dest=/home/{{ admin_user }}/apps/scala-{{ scala_version }}.deb

- name: Install scala
  shell: gdebi /home/{{ admin_user }}/apps/scala-{{ scala_version }}.deb
