# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
require 'vagrant-aws'

# Load the initialization file `init.yml`
@cmd = YAML.load_file('init.yml')
puts @cmd.inspect

# Create the Ansible groups
groups = {
  "admin" => [],
  "dse" => [],
  "flink" => [],
  "all_groups:children" => ["admin", "dse", "flink"]
}

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  config.vm.synced_folder '.', '/vagrant', :disabled => true
  config.vm.boot_timeout = 600
  (1..@cmd['Total']).each do |i|
    if i == 1
      name = "admin"
      groups["admin"] << name
    elsif i >= 7
      name = "flink-#{i - 7}"
      groups["flink"] << name
    else
      name = "dse-#{i - 1}"
      groups["dse"] << name
    end
    config.vm.define "#{name}" do | config |
      config.vm.hostname = name
      # Apply Ansible configuration to the last maschine
      if i == Total
        config.vm.provision :ansible do |ansible|
          ansible.playbook = "site.yml"
          ansible.groups = groups
          ansible.extra_vars = {
            "dse_version" => @cmd['DSE_Version'],
            "rstudio_server" => @cmd['RStudio_Server'],
            "shiny_version" => @cmd['Shiny_Version'],
            "spark_version" => @cmd['Spark_Version'],
            "maven_version" => @cmd['Maven_Version'],
            "tflow_version" => @cmd['TFlow_Version'],
            "scala_version" => @cmd['Scala_Version'],            
            "cluster_user" => @cmd['Master_User'],
            "cluster_password" => @cmd['Master_Pass']
          }
          ansible.limit = "all"
          ansible.verbose = "v"
          ansible.raw_ssh_args = ['-o ControlPersist=30m']
        end
      end
      
      # Specify AWS provider configuration
      config.vm.provider :aws do |aws, override|
        # Read the AWS authentication environmental variables
        aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
        aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
        # Specify the Key-pair
        aws.keypair_name = "devenv-key"
        # Specify the aws region
        aws.region = "us-west-1"
        # Specify the AMI type: ubuntu 14.04
        aws.ami = ""
        # Specify the EC2 Instance type
        aws.instance_type = ""
        # Specify the Security Group
        aws.security_groups = ""
        # Set the Name tag of the EC2 Instance
        aws.tags = {
          "Name" => name,
          "Description" => "DataStax Enterprise Node #{i}"
        }
        # Override Vagrant username, key defaults
        override.ssh.username = "ubuntu"
        override.ssh.private_key_patth = ENV['AWS_KEY_PATH']
        
      end  
    end
  end
end
