---
- name: Install pythons httplib2 library so that ansible uri module works
  apt: pkg=python-httplib2 state=present

- name: Call apache web service to find preferred maven download mirror
  uri: url=http://www.apache.org/dyn/closer.cgi?path=maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz&asjson=1 return_content=yes
  register: webResponse

- name: Download maven
  get_url:
    url: "{{webResponse.json.preferred}}{{webResponse.json.path_info}}"
    dest: /home/{{ cluster_user }}/apps/apache-maven-{{ maven_version }}-bin.tar.gz
    mode: 0440
    validate_certs: False

- name: Extract maven
  unarchive:
    src: /home/{{ cluster_user }}/apps/apache-maven-{{ maven_version }}-bin.tar.gz
    dest: /usr/local/
    copy: no
    creates: /usr/local/apache-maven-{{ maven_version }}

- name: Create symlink to maven version
  file:
    src: /usr/local/apache-maven-{{ maven_version }}/bin/mvn
    path: /usr/bin/mvn
    state: link
