---
- name: Download RStudio Shiny Server
  get_url: url=http://download3.rstudio.org/ubuntu-12.04/x86_64/shiny-server-{{ shiny_version }}-amd64.deb dest=/home/{{ cluster_user }}/apps

- name: Install RStudio Shiny Server
  shell: gdebi -n /home/{{ cluster_user }}/apps/shiny-server-{{ shiny_version }}-amd64.deb

- name: Copy Shiny samples
  shell: cp -R /usr/local/lib/R/site-library/shiny/examples/* /srv/shiny-server/