name: chkrd
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==2.7.13
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - pip:
        - git+https://github.com/fchollet/keras.git
