name: SparkaaS
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==2.7.13
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - imageio=2.1.2
    - pyqt=4.11.4
    - boto3
    - pip:
        - tensorflow==0.12.1
        - git+https://github.com/fchollet/keras.git
        - spark-sklearn
