---
- name: Create notebooks directory
  file:
    state: directory
    dest: /home/{{ cluster_user }}/notebooks
    owner: "{{ cluster_user }}"
    group: "{{ cluster_user }}"

- name: Install Jupyter for Python3
  pip: name=jupyter executable=pip3

- name: Install Jupyter for Python2
  pip: name=jupyter

- name: Install Python2 kernel
  command: python2 -m ipykernel install

- name: Generate notebook config
  command: jupyter notebook --generate-config
  become_user: "{{ cluster_user }}"

- name: Create Jupyter default config
  template:
    src=jupyter_notebook_config.py.j2
    dest=/home/{{ cluster_user }}/.jupyter/jupyter_notebook_config.py
    owner={{ cluster_user }}
    group={{ cluster_user }}

- name: Unset the Jupyter runtime id in .bashrc
  lineinfile:
    dest: '/home/{{ cluster_user }}/.bashrc'
    line: 'unset XDG_RUNTIME_DIR'
    regexp: '^(# *)?unset XDG_RUNTIME'
  become_user: "{{ cluster_user }}"

# The following need to be researched as the destination directory doesn't exist in jupyter.
#- name: Disable notebook warnings
#  template: src=disable-warning.py.j2 dest=/home/{{ cluster_user }}/.ipython/profile_default/startup/disable-warning.py
