---
- name: Installs pip
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - python-pip
    - python-yaml
    - openjdk-8-jre
    - docker.io
  become: yes
  become_method: sudo

- name: Installs pip dependencies
  pip: name={{item}} state=present
  with_items:
    - pexpect
    - boto
    - virtualenv
  become: yes
  become_method: sudo


- name: Creates aws credentials directory
  file: path=/home/vagrant/.aws state=directory


- name: Create aws credentials configuration
  template: src=aws_credentials.template dest=/home/vagrant/.aws/credentials force=yes
