---

- name: Adds dcos-kafka
  shell: /home/vagrant/dcos-cli/bin/dcos package install kafka --yes
  ignore_errors: True

- name: Adds dcos-cassandra
  shell: /home/vagrant/dcos-cli/bin/dcos package install cassandra  --yes
  ignore_errors: True

- name: Copies dcos-spark config
  copy: src=spark-options.json dest=/tmp/spark-options.json

- name: Adds dcos-spark
  shell: /home/vagrant/dcos-cli/bin/dcos package install spark --yes
  ignore_errors: True

- name: Adds kafka-brokers
  shell: /home/vagrant/dcos-cli/bin/dcos kafka broker add 0..2 --port 9092
  register: brokers_added
  until: brokers_added|success

- name: Starts kafka-brokers
  shell: /home/vagrant/dcos-cli/bin/dcos kafka broker start 0..2
  when: brokers_added|success
  register: brokers_started
  until: brokers_started|success