---
- name: Installing Deependencies
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
    - libssl0.9.8
    - python-software-properties

- name: Adding Oracle java repository
  shell: add-apt-repository -y ppa:webupd8team/java

- name: Updating machine
  apt: update_cache=yes

- name: Preparing for java installation
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: Installing oracle java
  shell: DEBIAN_FRONTEND=noninteractive apt-get -y install oracle-java8-installer oracle-java8-set-default

- name: Adding DataStax Repository
  shell: echo "deb http://datastaxrepo_gmail.com:utJVKEg4lKeaWTX@debian.datastax.com/enterprise stable main" | sudo tee -a /etc/apt/sources.list.d/datastax.sources.list

- name: Adding DataStax Repository key
  apt_key: url=https://debian.datastax.com/debian/repo_key state=present

- name: Updating machine
  apt: update_cache=yes

- name: Installing OpsCenter
  apt: pkg=opscenter state=installed update-cache=yes
  register: opscenterd

- name: Starting OpsCenter
  service: name=opscenterd enabled=yes state=started