---
# Establishing a base library configuration for all instances
- name: Updating apt repository
  apt: update_cache=yes
  become: yes

- name: Install build dependecies for scipy
  apt: pkg=python-scipy state=build-dep
  become: yes

- name: Install common packages
  apt: pkg={{ item }} state=present
  with_items:
    - python-pip
    - python-scipy
  become: yes

- name: Install common Python libraries
  pip: name={{ item }} state=present
  with_items:
    - scikit-learn
    - Theano
    - spark-sklearn
    - keras
  become: yes

- name: Install TensorFlow
  pip: name=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-{{ tflow_version }}-cp27-none-linux_x86_64.whl state=present
  become: yes